...

diff --git a/api/Dockerfile b/api/Dockerfile
--- a/api/Dockerfile
+++ b/api/Dockerfile
@@ -1,16 +1,19 @@
-FROM python:3.9-slim
+FROM node:18-alpine AS base
 
-# Set working directly in the container
-WORKDIR /usrsrc/app
+WORKDIR /app
 
-# Copy the dependencies file to the working directly
-COPY requirements.txt ./
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Install any needed packages from requirements.txt
-RUN pip install --no-cache-dir -r requirements.txt
-
-# copy the content of the local src directory to the working directory
 COPY . .
 
-# Run the app
-CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80" ]
+RUN npm run build
+
+EXPOSE 3000
+
+CMD ["npm", "start"]
